name: Update Crypto Prices and Analysis

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-crypto-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run Crypto Movers Analysis
        env:
          DISCORD_CRYPTO_MOVERS_WEBHOOK: ${{ secrets.DISCORD_CRYPTO_MOVERS_WEBHOOK }}
        run: |
          cd discord_bot
          python crypto_movers.py
