name: Update Crypto Prices and Analysis

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-crypto-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run Crypto Movers Analysis
        env:
          DISCORD_CRYPTO_MOVERS_WEBHOOK: ${{ secrets.DISCORD_CRYPTO_MOVERS_WEBHOOK }}
        run: |
          python discord_bot/crypto_movers.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.CRYPTO_DISCORD_BOT }}
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add discord_bot/crypto_data/
          git commit -m "Update crypto prices [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SignalChaser/Youtube.git
